### ISSUE TITLE
Event: [Cityname] Games

### ISSUE THREAD

**Issue by AnastaseAlex** [TechpriestEnginseer/Community-Patch-Events-Development#10]
Requires: ancient or classical era, has pantheon

The city of [Cityname] has been holding sport competitions in honor of [name of the pantheon].
They have steadily gained popularity.

Case1: We should promote them more!
Requires Arena, spend 50 gold: Arena gains +2 tourism

Case2: Let the population rejoice!
requires local unhappyness <2, City has a 5 turn WLTKD

Case3: Let us use this occasion to show off our martial prowess!
requires garisson unit, friends with at least 1 city-state, gain +5 resting point with all friendly city-states.

Case4: So many people gathering without an army present was sure to cause problems...
Have no garrison unit, 2 barbarian units spawn near the city.

Case5: This could do wonders for our economy!
requires market, being bellow trade units limit, spend 70 gold, gain a caravan.

Case6: the gods will be pleased
Have garrison in the city, you gain 10 faith per population in the city.

**Comment by Hokath** [comment]
Will do something along these lines.

**Comment by AnastaseAlex** [comment]
Yeah, the important part for me is the flavor idea, and interesting choices where if you do not have any of the positive possibles you get penalized, but I do not care that much about the precise bonuses.

**Comment by Hokath** [comment]
ok.
Unfortunately less than max trade routes is only for player events,
whereas this is a city event. will probably make that choice require an incoming trade route to fire, and just give more gold, maybe a point of science, for a set duration (pseudo trade route)

**Comment by Hokath** [comment]
finished, pending testing
