### ISSUE TITLE
Event idea: Ancient Policies

### ISSUE THREAD

**Issue by AnastaseAlex** [TechpriestEnginseer/Community-Patch-Events-Development#11]
requires researched techs > 12 exipries at medieval

Text: The rate at which we are acumulating new knowledge is phenomenal! Some elders however are afraid this changes too much our way of life.

Case 1: You are right, we need to preserve our traditions!
Requires Tradition
Monuments get +1 culture

Case 2: The world is a place for the young! Involve them more in the councils.
Requires Progress
Councils get +1 science

Case 3: The strength of the nation is more important than a stable way of life.
Requires Authority
Barracks get +1 production

Case 4: We must not compromise between our choices.
Requires two policy branches open.
Cities get +1 science  if you have progress, +1production if you have authority, +1 culture if you have tradition

Case 5: They just want us to recognise it was all thanks to the wisest of them.
Requires three policy branches open.
Free great peson.

Case 6: I have other things that require my attention.
No requirements, 
no effects.

**Comment by TechpriestEnginseer** [comment]
We're trying to stray away from policy events for balance reasons.

**Comment by AnastaseAlex** [comment]
If I understand correctly however the events fire off randomly. You might get an event any turn, and if you do it chooses one from a pool of events?

If so is there a set probability of it happening? The bonuses are minor enough that unless you have taken 3 policy trees before medieval, the rewards are not that powerful, no?

Instead of a great person we can give great person points too.

**Comment by TechpriestEnginseer** [comment]
Closed due to inactivity.
