### ISSUE TITLE
Event: Strange Bones

### ISSUE THREAD

**Issue by AnastaseAlex** [TechpriestEnginseer/Community-Patch-Events-Development#12]
Required: farm ERA<Modern

While tilling their fields in CITYNAME, some farmers have found strange bones. One of them had three horns on it. The population seeks your guidance as to how to interpret this:

Case1: Have the army bury them back in! Such creatures should never see the light of day.
Local Happyness +1 for 20 turns. 
ERA=Ancient to Medieval Has guarison

Case2: They are the bones of dragons and mythical creatures! Let us set them in the shrine to strengthen them!
Shrine +1 faith.
Has no religion, has shrine.

Case3: We should try to understand why there are no creatures like that any more.
Gain 200 \* era science.
Medieval to rennaisance, has university

Case4: These should be exibitted in the museum!
Gain one cultural artifact.
Has Museum, has empty artifact slot

Case5: You bring me peasants' complaints now?
-2 local happyness for 20 turns

**Comment by Hokath** [comment]
I'll knock something together soon

**Comment by Hokath** [comment]
done
