### ISSUE TITLE
Gazebo Message

### ISSUE THREAD

**Issue by Hokath** [TechpriestEnginseer/Community-Patch-Events-Development#13]
Folks,

Gazebo would like to move all our events to the (7) mod that currently contains Enginseer's stuff (iirc?)
[Requiring full vox pop install therefore]

This is for modularity and version control while we make more stuff.

Thoughts?

**Comment by AnastaseAlex** [comment]
I think that is a good idea for people that only know about the (7) mod. There are some good events in here.

**Comment by TechpriestEnginseer** [comment]
I was already making all the events to put into my (7) mod anyway.

So, is this all of our events or all of the events including the previously made?

**Comment by Hokath** [comment]
I think all of the events on this github

**Comment by Hokath** [comment]
Then, when we are 'done', I think he wants to compile them all (including his) together.

How will we/you go about putting the files into the mod?

**Comment by Hokath** [comment]
Note to self:
After completing unique events, sort all the events into ~3 categories of evil, trade off and major

**Comment by Hokath** [comment]
[Test version of CP](https://drive.google.com/file/d/0BwqQJAI2m04UdVc1Um1wc2tTeFU/view) with...

```
 Event Class - You don't have to set this, however you can use the follow categories to give players <!--the options to enable/disable certain types of Events:
            EVENT_CLASS_GOOD
            EVENT_CLASS_BAD
            EVENT_CLASS_NEUTRAL
            EVENT_CLASS_TRADE
            EVENT_CLASS_CIV_SPECIFIC
    -->
        <Column name="EventClass" type="text" reference="EventClassTypes(Type)" <!--default="NULL"/>
```

DLL elements for the various classes! All hail G.

**Comment by TechpriestEnginseer** [comment]
Wonder if we can make new EventClassTypes then...

**Comment by Hokath** [comment]
I guess not easily?
If you think we need new types we can just ask for them.
