### ISSUE TITLE
Natural Wonder events testing

### ISSUE THREAD

**Issue by Hokath** [TechpriestEnginseer/Community-Patch-Events-Development#14]
Comrades,

I've finished a set of city events that trigger when a natural wonder is within working distance. 
One for each wonder.

Could I have some feedback? Especially on the delay between procs. You can find them, with a modfile to run as a separate mod and a readme, under my part of the code section.

**Comment by AnastaseAlex** [comment]
will do

**Comment by AnastaseAlex** [comment]
The lake victoria event only gave me the choice to build an hydroelectric plant for 750 gold... during medieval times. It happens about once per era which is ok, I guess, but I would rather it happened once per two eras.

**Comment by Hokath** [comment]
ah yeah i see that error.
but yeah you think that about twice as long between procs? (i agree with longer)

**Comment by Hokath** [comment]
Ok i changed the chance delta, see how this affects the duration between events in your next game.

**Comment by AnastaseAlex** [comment]
Also it is sad to see the Natural wonders do not retain their extra yields when you conquer them.
Yeah, twice as long should do the trick.

**Comment by Hokath** [comment]
Yes that is annoying.
I wonder if you lose a city and recapture it, what happens?
