### ISSUE TITLE
Set of ideas

### ISSUE THREAD

**Issue by Hokath** [TechpriestEnginseer/Community-Patch-Events-Development#15]
Just jotting down my ideas so I don't forget.

Still need to buff up the numbers of events.
Going to have a set based on each advisor (easy theming, so lazy)

Structure:
Player event triggers: yes or no (no cost - neutral)
If no: ends
If yes: 3 player events can trigger (good, trade, bad)
          3 city events can trigger (good, trade, bad)

Spread them out over periods, say classical-renaissance, medieval-industrial, renaissance-modern, industrial-postmodern, s.t. only 2 overlap.

**Comment by Edaka** [comment]
This isn't really the place to put it, but I know no better so here it goes. I've been following the uploads you do to this repository for a while, Hokath. You're doing the God's work; the amount of new, enticing events you put up over time is simply mind-boggling. Have you considered promoting your mod-mods over at the forum? I don't think you or anybody else has given them a proper exposure yet, and they certainly deserve it.

**Comment by Hokath** [comment]
Wow, Edaka, thank you so much. With Events rubbing people different ways, I'm glad someone else is on the same track as me.

I want to do a few games with what I have, check the chances of triggering and perhaps find some errors.
Then the plan is to take all the events on the repository, compile them into one modmod and then add that to the automatic installer as module (7).

**Comment by TechpriestEnginseer** [comment]
What he said.

**Comment by Edaka** [comment]
I see, but I think that a larger audience of testers would help speed up the process of finding bugs. Maybe a beta version?

**Comment by Hokath** [comment]
Im still waiting for Gazebo to push a new handle to let me roll out instant yields to all cities (you'll notice events that say -1 pop in all cities dont actually work at the moment), but after that we can go to beta.
