### ISSUE TITLE
Austria's unique event error

### ISSUE THREAD

**Issue by Edaka** [TechpriestEnginseer/Community-Patch-Events-Development#16]
I was going through logs (to see what mod has caused AI major civs stop building workboats) and found this in Database.log

> [2559.165] table EventChoices has no column named CapitalOnly
> [2559.165] In Query - insert into EventChoices('Type', 'Help', 'Description', 'IsOneShot', 'RequiredAnywhereBuildingClass', 'WLTKDTurns', 'EventDuration', 'Expires', 'EventBuildingClassGlobal', 'CapitalOnly', 'EraScaling') values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
> [2559.165] In XMLSerializer while updating table EventChoices from file Austria.xml.

Don't know if it means anything, but here it is.

**Comment by Edaka** [comment]
Also found this further down the log:

> [2614.108] Invalid Reference on EventChoices.RequiredAnywhereBuildingClass - "BUILDINGCLASS_TOURISM_CENTER" does not exist in BuildingClasses

Don't know if that's any of your events, guys. That's the only line referencing it.

**Comment by TechpriestEnginseer** [comment]
Hokath didn't you say you were making some sort of unique event for Austria?

**Comment by Hokath** [comment]
yeah its definitely mine, any and all database errors you see are. gazebo doesn't tolerate them in the release versions

**Comment by Hokath** [comment]
(btw these are my typos, the austria events wont fire that's it. i have uploaded the fix)
By the way if you do test austria before me, I am seeing if a certain promotion parameter works. If it does, their promotion will work in reverse, and the strength of a unit will increase the further they are from the capital.
