### ISSUE TITLE
Some minor oddities

### ISSUE THREAD

**Issue by Edaka** [TechpriestEnginseer/Community-Patch-Events-Development#22]
Did a quick play session and found some minor things, mostly related to text.
1. The title for this event is too long to fit - perhaps wanna duplicate it in the description.
   ![20160725195051_1](https://cloud.githubusercontent.com/assets/12978597/17112718/e9c2f834-52af-11e6-8d0a-975095d02d42.jpg)
2. Related to the same event - the actual description is messed up for some reason. Looking at the xml, I see this : `Pay {2_InstantYield} in compensation and lose {4_GPChange} to further relations.` Looks fine, but the word sequence is wrong in-game, and it doesn't show Great Diplomat point change. Perhaps due to the fact that {2_InstantYield} is both minus gold and culture and it can't show them both at the same time?
3. In SolomonsMines.xml, line 255: 

> On the surface, these bizzare troglodytes will be no match for **are** well-armed militia.

Should be **our** well-armed militia, it seems.
1. In the same file, 3rd choice's description mentions paying gold to construct a well, but in fact it also requires a watermill at the same time. Intentional?

**Comment by Hokath** [comment]
1./2. I just got this too. I think its because the city doesnt have any great diplomat points to lose. I reworded it so it makes sense even if the change is blank.
3. tyvm
4. yeah it should allow you a well when you have a watermill (so you can have both)

**Comment by Edaka** [comment]
Oops, just noticed the screenshot. Heh. Anyway, regarding 4: the way I got it is you can't take the event choice without a watermill, right? That way it actually restricts the player, even though it makes it possible to have both a watermill and a well. 

Oh, by the way, wanted to add something about that Foreign bad event (2. in the OP): I seem to be getting it really frequently, sometimes with just a couple turns inbetween, sometimes I'll get like two or three in a row with no other events inbetween. Pretty frequent.

**Comment by Hokath** [comment]
hehe

Yes, so there is another option that lets you have a watermill if you had a well. I dont want the AI being silly and picking the wrong one, or the player for that matter.

Yeah the frequency is high, ill turn it down

**Comment by Edaka** [comment]
Ah, so the two are pretty much mirror opposites. Gotcha. Did'nt realize that because I actually had a well in the city this event fired, so it didn't show up as a lacking requirement, only the gold did.

**Comment by Hokath** [comment]
yeah exactly
