### ISSUE TITLE
attempt to index global 'pPlayer' (a nil value)

### ISSUE THREAD

**Issue by biship** [TechpriestEnginseer/Community-Patch-Events-Development#24]
Running 7/26 build of CBP. Getting hundreds of these in lua.l.og:
TheLastGoodbye.lua:421: attempt to index global 'pPlayer' (a nil value)

(Oh this is for Civ and Reform v1. The steam web page directed me here)

**Comment by TechpriestEnginseer** [comment]
Ooh. I have forgotten to localize the variable, so now it's getting everything. Thanks!
