### ISSUE TITLE
Why do we figth?

### ISSUE THREAD

**Issue by Mitchsp** [TechpriestEnginseer/Community-Patch-Events-Development#27]
Hi, testing for first time this event's pack and it's great!, but I've find a problem and this option isn't working for me:

![captura](https://cloud.githubusercontent.com/assets/13163824/17504576/7e5a3b42-5dfa-11e6-98ee-0829bb9d841d.PNG)

![captura](https://cloud.githubusercontent.com/assets/13163824/17504597/b1dd9b08-5dfa-11e6-96b0-b8c3b520604c.PNG)

The 1 faith point comes from the pantheon

**Comment by TechpriestEnginseer** [comment]
Yeah it's been fixed thanks!
