### ISSUE TITLE
Venice Unique Event

### ISSUE THREAD

**Issue by pandasnail** [TechpriestEnginseer/Community-Patch-Events-Development#28]
Venice has a Unique Event where I could have chosen to get 5 Great Galls (and 5 Gardens!) in the (late) Classical Era. That would have been death to my enemies (and 'friends') This is my first game with the UE system, unless they'e all that good, that could a tech or era prereq imo.

With all the new events, they really truly feel random and unexpected now! Great work!

**Comment by Hokath** [comment]
Yes, I balls'd that one up. For some reason the Unit was a Dromon in my head, clearly a Galleass!!
I'll push the prereq back to Guilds.
