### ISSUE TITLE
Can't select city event

### ISSUE THREAD

**Issue by joosegoose** [TechpriestEnginseer/Community-Patch-Events-Development#30]
First of all, a disclaimer (sorry if this is due to user error and I'm wasting time) - I'm using Vox Populi as a modpack and trying out loading Events through the mod menu for compatibility reasons.

The issue - I'm getting a city event early in the game but I am unable to do anything with it. The Lua log seems to indicate an issue with the event I believe, though I have no idea what it could mean.

[Logs.zip](https://github.com/TechpriestEnginseer/Community-Patch-Events-Development/files/416192/Logs.zip)

**Comment by TechpriestEnginseer** [comment]
http://forums.civfanatics.com/showthread.php?t=559644

Look at these instructions and report to me what's the name behind ID 45 in table CityEvents

**Comment by joosegoose** [comment]
Assuming I'm using the utility correctly, City Events only gives 35 IDs, whereas I've had 45 and 41 now pop up as errors in Lua logs.

**Comment by joosegoose** [comment]
City Event 45 - CITY_EVENT_DESERTVOICES - EVENT_CLASS_GOOD

City Event 41 (also popped up as an issue with a new game) - CITY_EVENT_JUNGLEFEVER - EVENT_CLASS_BAD

**Comment by TechpriestEnginseer** [comment]
It's an issue with the modpack. I don't know how the modpack works, so I can't do anything to solve it. Sorry.

**Comment by joosegoose** [comment]
It's okay, if anything I should apologize for reporting user error...I had a suspicion my setup would not work 100%.

I would simply place it in a modpack directly but whenever I try to create a pack with this mod, it manages to mute all of the audio for the entire game somehow.

**Comment by TechpriestEnginseer** [comment]
Then ask how is the audio added in the modpack.

**Comment by joosegoose** [comment]
I posted in the MPMPM thread about it, there was another post from a couple months ago where someone experienced the exact same issue with a different, older mod. Cicero225 seemed interested in that instance (wanted to work on compatibility), so I mentioned that I was having the same issues with this project as well. I'm not sure he's been on the forums to see it yet.
