### ISSUE TITLE
Problem with an event, don't remember the name

### ISSUE THREAD

**Issue by Mitchsp** [TechpriestEnginseer/Community-Patch-Events-Development#31]
Sorry, forgot the name and can't find in the xmls. Was about a hot summer, with options to pass the event without harm being near of an ice tile, losing -50? production or use the religious authority to lose 30 faith and gain 60 production.

This last option is the bugged one, adding instead 30 faith and 60 production.

**Comment by Hokath** [comment]
well fielded, fixed for next version
thanks.
