### ISSUE TITLE
Lake Victoria event crash

### ISSUE THREAD

**Issue by joosegoose** [TechpriestEnginseer/Community-Patch-Events-Development#32]
No longer using the setup I unsuccessfully tried in [this](https://github.com/TechpriestEnginseer/Community-Patch-Events-Development/issues/30) issue. Everything is working great, save for a consistent crash I get with the Lake Victoria event. I only know it's this event from SQLiteSpy--the game immediately crashes upon clicking the City Event icon, every time.
[Logs.zip](https://github.com/TechpriestEnginseer/Community-Patch-Events-Development/files/419517/Logs.zip)

**Comment by TechpriestEnginseer** [comment]
Interesting...

**Comment by TechpriestEnginseer** [comment]
I see the problem. For future references, @Hokath,

```
        <Row>
            <Type>CITY_EVENT_NW_LAKE_VICTORIA_CHOICE_2</Type>
            <Help>TXT_KEY_CITY_EVENT_NW_LAKE_VICTORIA_HELP_CHOICE_2</Help>
            <Description>TXT_KEY_CITY_EVENT_NW_LAKE_VICTORIA_DESCRIPTION_CHOICE_2</Description>
            <IsOneShot>true</IsOneShot>
            <RequiredBuildingClass>BUILDINGCLASS_UNIVERSITY</RequiredBuildingClass>
            <RequiredNoActiveCityEventChoice>CITY_EVENT_NW_LAKE_VICTORIA_CHOICE_3</RequiredNoActiveCityEventChoice>
        </Row>
        <Row>
            <Type>CITY_EVENT_NW_LAKE_VICTORIA_CHOICE_3</Type>
            <Help>TXT_KEY_CITY_EVENT_NW_LAKE_VICTORIA_HELP_CHOICE_3</Help>
            <Description>TXT_KEY_CITY_EVENT_NW_LAKE_VICTORIA_DESCRIPTION_CHOICE_3</Description>
            <IsOneShot>true</IsOneShot>
            <PrereqTech>TECH_FERTILIZER</PrereqTech>
            <RequiredNoActiveCityEventChoice>CITY_EVENT_NW_LAKE_VICTORIA_CHOICE_2</RequiredNoActiveCityEventChoice>
        </Row>
```

RequiredNoActiveCityEventChoice should never require each other or else it will cause a leak eventually leading to a crash.

I'll do a fix immediately, but any game won't be save-game compatible.
