### ISSUE TITLE
Brazil UE Pracinha bug

### ISSUE THREAD

**Issue by joosegoose** [TechpriestEnginseer/Community-Patch-Events-Development#34]
![20160822021458_1](https://cloud.githubusercontent.com/assets/11132095/17847391/55a78768-6813-11e6-9000-a60e5b7f3a14.jpg)

A bit early for Pracinhas, I think...

I think I see the cause of the error, Pracinhas are supposed to be recruited in every city for choice #5, but:

`<EventChoiceType>EVENT_BRAZIL_UE_CHOICE_3</EventChoiceType>
            <UnitType>UNIT_BRAZILIAN_PRACINHA</UnitType>
            <Quantity>1</Quantity>`

Choice #3 is supposed to be:
`<Row Tag="TXT_KEY_EVENT_BRAZIL_UE_HELP_CHOICE_3">
            <Text>Against the elites and the clergy, spend {1_YieldCost} to reduce [ICON_RESEARCH] Illiteracy thresholds by 10%. All Universities generate +2 [ICON_CULTURE] Culture.</Text>`

**Comment by Hokath** [comment]
good catch, will update, thanks
