### ISSUE TITLE
Portugal UE: Typo?

### ISSUE THREAD

**Issue by 8h42** [TechpriestEnginseer/Community-Patch-Events-Development#36]
cf. 
(7) Community Events (v 2)\XML\Hokath\CivilizationEvents.xml
<Row Tag="TXT_KEY_EVENT_PORTUGAL_UE_HELP_CHOICE_2">

It seems to me that

`{1_InstantYield}`

should be 

`{2_InstantYield}`

**Comment by Hokath** [comment]
right you are
