### ISSUE TITLE
Advisor Events: Foreigner Murdered

### ISSUE THREAD

**Issue by 8h42** [TechpriestEnginseer/Community-Patch-Events-Development#38]
I can't see the effect of {4_GPChange}.

![foreigner](https://cloud.githubusercontent.com/assets/11933188/18554868/a5b3be48-7ba0-11e6-8ac1-cc8c3256185a.png)

Vox Populi: ver 9/12
Community Events: ver 9/11

**Comment by TechpriestEnginseer** [comment]
Do you have CSD?

**Comment by 8h42** [comment]
Yes, I do.
This event mod requires CSD, doesn't it?

**Comment by TechpriestEnginseer** [comment]
Huh... I'll have to do further testing.

**Comment by Hokath** [comment]
The reason for this is that if you don't have any Great Diplomat Points, it just shows up as a space rather than saying "0".

**Comment by 8h42** [comment]
Good to know.
Thank you.
