### ISSUE TITLE
TXT_KEY_BUILDING

### ISSUE THREAD

**Issue by 8h42** [TechpriestEnginseer/Community-Patch-Events-Development#39]
I found a few TXT_KEY_BUILDING tags.

TXT_KEY_BUILDING_MONASTERY
- A Poverty Of Aspiration: Choice 2

![monastery](https://cloud.githubusercontent.com/assets/11933188/18620479/86d2fcfe-7e4e-11e6-9fa0-5a5c5166084f.png)

---

TXT_KEY_BUILDING_STADIUM
- Celts UE: Choice 6
- Iroquois UE: Choice 6

![stadium](https://cloud.githubusercontent.com/assets/11933188/18620482/8be123ce-7e4e-11e6-8e0c-65e3bcbe91fc.png)

---

Mod List
- VP EUI set (9/12)
- Community Events (9/11)
- IGE

**Comment by TechpriestEnginseer** [comment]
Actually, I think that's a bug with Gazebo's things. Report it to him.

**Comment by 8h42** [comment]
All right.
Thank you for your quick reply.

**Comment by TechpriestEnginseer** [comment]
Has been finished.
