### ISSUE TITLE
Event chain idea: Oracle's Protent

### ISSUE THREAD

**Issue by AnastaseAlex** [TechpriestEnginseer/Community-Patch-Events-Development#4]
Requires: The Oracle in city, at war with an other civilization.

Text: The wise priestess of the oracle of CITYNAME sent their cryptic warning:
"Should you attack (closest city of civ at war) a great empire will fall"

Case1: Great news! We will win this war as soon as we take (closest city of civ at war)!
Overlay text: Good things will happen if you conquer (closest city of civ at war) in the next 7 turns. Failing this mission will have negative consequences.

Case2: This is a dire warning! We are overextending ourselves! We should strive to make peace as soon as possible.
Overlay text: Good things will happen if you make peace with (civ at war) in the next 7 turns.
Failing this mission will have negative consequences.

Case3: Ignore them, the populace can be fooled but we make our own destiny.
CITYNAME (with orcae) has 2 local unhappyness for 10 turns

Event: city conquest within 7 turns.
If you choose this and conquer the city in 7 turns, all your units gain (citypopulation when conquered \* 3 \* currentage) xp. You gain 200 gold.
If you choose this and don't conquer the city in 7 turns, 1 barbarian unit / 2 populations of (closest city of civ at war) is spawned near one of your cities.

Event: peace within 7 turns.
If you choose this and make peace in 7 turns, you enter a 5 turn golden age. You gain 200 gold.
If you choose this and don't make peace in 7 turns, military upkeep is doubled for 10 turns. (scaling with game speed)

**Comment by TechpriestEnginseer** [comment]
Looks great, but it looks it may needs Lua in having a "mission"

**Comment by AnastaseAlex** [comment]
damn. I need to read more about the limitations of what xml can do. Can it not certainly fire 7 turns later and check if you have met the criteria? I thought I had read you had that option.

**Comment by TechpriestEnginseer** [comment]
We do, but we're focusing purely on XML-events for now.

**Comment by AnastaseAlex** [comment]
ok, I guess we can forget this one then :)
