### ISSUE TITLE
Missing parameters 

### ISSUE THREAD

**Issue by 8h42** [TechpriestEnginseer/Community-Patch-Events-Development#40]
Some parameters don't show up correctly. 

Arabia UE: Choice 5
![arabia 5](https://cloud.githubusercontent.com/assets/11933188/18620719/eb932dc2-7e52-11e6-9732-cd669921e206.png)

---

Ethiopia UE: Choice 5
![ethiopia 5](https://cloud.githubusercontent.com/assets/11933188/18620720/f0b2afb2-7e52-11e6-885a-359ff87c14fd.png)

---

Ethiopia UE: Choice 6
![ethiopia 6](https://cloud.githubusercontent.com/assets/11933188/18620725/06723368-7e53-11e6-8836-70663c1672e3.png)

---

Maya UE: Choice 3
![maya 3](https://cloud.githubusercontent.com/assets/11933188/18620723/fae5c56e-7e52-11e6-9de0-3aedea45584b.png)

---

Mod List
- VP EUI set (9/12)
- Community Events (9/11)
- IGE

**Comment by Hokath** [comment]
I'll take a look

**Comment by Hokath** [comment]
uploaded the fixes
Thanks for reporting these
