### ISSUE TITLE
Can EconomicCityTrade have a choice that doesn't cost Gold?

### ISSUE THREAD

**Issue by pandasnail** [TechpriestEnginseer/Community-Patch-Events-Development#43]
Could have other negative consequence of course, I'd prefer a 'not interested' choice like the Lighthouse event has tho.

(This is the event where its pay 750 gold (by the time you get it, its scaled to that) to get yields added to villages. Making the yields better is I guess another choice.)

**Comment by Hokath** [comment]
Ok.
Do you not think the rewards are good enough for the gold cost then?

Edit: the thing about adding a "not interested" option is that event may fire when you can't afford it, and so the opportunity is completely wasted. I find that really, really annoying personally, hence the lack of such a choice.

**Comment by pandasnail** [comment]
I guess I see what you are saying about the not interested choice.

Maybe I'm underrating the yields, but the event comes so late that the 6 science or whatever doesn't feel like anything, except for unhappiness I guess. That doesn't mean it actually isn't tho. The complicated thing is that some games I have so much gold I'd happily pay 5000 gold for like 1 Science. And then other games I need constant refreshing of units and such. Maybe in those games I should turn down the economic advisor trip in the first place? Idk

**Comment by Hokath** [comment]
Yeah idd there is quite high variance on gold. I'll tone down the cost a little, 150 per era -> 125 per era

**Comment by Hokath** [comment]
I further decreased the cost of the early choices and increased the reward and the requirements of the two end ones.
