### ISSUE TITLE
No events for Theocratic Rule?

### ISSUE THREAD

**Issue by Ta1kavarpu** [TechpriestEnginseer/Community-Patch-Events-Development#45]
I found out about this mod recently and decided to test it. While going through the files for religion specific events I noticed there is no file for Theocratic Rule. There's no events for Theocratic Rule?

**Comment by TechpriestEnginseer** [comment]
hokath retired before the addition of theocratic rule.

and I'm working on a formula right now to make events go wheee

**Comment by TechpriestEnginseer** [comment]
Thanks for the notice!

**Comment by TechpriestEnginseer** [comment]
Done.
