### ISSUE TITLE
Sweden UE Choice #2

### ISSUE THREAD

**Issue by HungryForFood** [TechpriestEnginseer/Community-Patch-Events-Development#46]
While looking through the code to find out what each UE does, I found that the string for Sweden's UE Choice #2 says that it will cause Snow tiles to yield 2 Culture. However, the relevant code appears to have only a value of 1 for the Culture yield. Looking at the codes on Github, it appears to still be so.

		<Row>
			<EventChoiceType>EVENT_SWEDEN_UE_CHOICE_2</EventChoiceType>
			<TerrainType>TERRAIN_SNOW</TerrainType>
			<YieldType>YIELD_CULTURE</YieldType>
			<YieldChange>1</YieldChange>
		</Row>

Also it seems that yields for Ice does not work.

**Comment by TechpriestEnginseer** [comment]
Thanks!
