### ISSUE TITLE
Religious decisions don't gain science.

### ISSUE THREAD

**Issue by aldebaran1997** [TechpriestEnginseer/Community-Patch-Events-Development#51]
I enacted 'Hold a Holy Festival' decision which says me to give lump sum of science and faith, but it only gives faith. I think I experienced these kind of happening, and it always doesn't work for only science.

**Comment by TechpriestEnginseer** [comment]
is this E&D or CE?

**Comment by aldebaran1997** [comment]
Hah, sorry. It's E&D I guess.

**Comment by TechpriestEnginseer** [comment]
Oh no, I'll fix it. Should be left opened when I am ready to update E&D again.
