### ISSUE TITLE
America UE Choice 3 and 5

### ISSUE THREAD

**Issue by HungryForFood** [TechpriestEnginseer/Community-Patch-Events-Development#59]
In the string, it is stated that choice 3 gives away horses for fur, and gold. However, in the code, these resource changes are mistakenly assigned to choice 2.

Same goes for the sugar in choice 5, which is assigned to choice 2 incorrectly.

Present in the latest steam workshop version.

By the way, I think choice 3 feels like a penalty instead of a bonus, because 4 horses is a lot to give away.

**Comment by Hokath** [comment]
Well spotted. I agree 4 is a lot on some less resource-abundant maps. Reduced to 2.
