### ISSUE TITLE
Event idea: New Luxuries

### ISSUE THREAD

**Issue by AnastaseAlex** [TechpriestEnginseer/Community-Patch-Events-Development#6]
Requires: scout_class unit lvl 2+ era_number, on top of a resource [citrus, dyes, cotton, chocolate, coffee, tea, spices, nutmeg] and distant from capital at least 20 tiles (scalling with mapsize)

Our explorer spent some time learning to appreciate [luxury resource]. Should he reach the capital in the next 10 turns, he might manage to bring us some grow-able seeds.

case1: let him speed his way to us!
(If the scout/explorer/ etc gets to the capital, that [luxury resource] spawns on a tile near your capital)

case 2: enough resting: he has to find out more about the world!
(the unit is fully healed)

**Comment by TechpriestEnginseer** [comment]
AIs can't use case 1.

**Comment by AnastaseAlex** [comment]
ok, how about pay 100 gold \* era, loose the scout/explorer gain the luxury?

**Comment by TechpriestEnginseer** [comment]
Sounds doable.

**Comment by AnastaseAlex** [comment]
We could change it to capital gets +2 local happyness if you want to avoid lua.

**Comment by TechpriestEnginseer** [comment]
Fair enough.

**Comment by TechpriestEnginseer** [comment]
Done. The event will grant +2 happiness for 100*Era or level the scout to a higher level for finding a secret treasure.
