### ISSUE TITLE
Can't progress past mod selection screen

### ISSUE THREAD

**Issue by maptap** [TechpriestEnginseer/Community-Patch-Events-Development#62]
[Logs.zip](https://github.com/TechpriestEnginseer/Community-Patch-Events-Development/files/1602102/Logs.zip)

By the select mod screen I select all 6 vox populi mods plus community events. I then click next and my cursor turns into the spinning world thing to show it was loading. After a few seconds I hear a click like I pressed something in game and the cursor turns back into an arrow.

However, the screen does not change - it remains at the select mods screen with "loading please wait". It stays like this for ever - I have waited 10 minutes.

Then I pull up the task manager to end Civ 5. After that when I start any game (civ 5 or otherwise) I get a message saying the computer cannot find a valid direct 3d device. I must restart my computer to get it working. This does not happen when I start a game with just Vox Populi, or any other mod.

I have tried reinstalling Civ 5 and vox populi to no effect.

Thanks!

**Comment by TechpriestEnginseer** [comment]
That's peculiar. I'll need ur (7) Community Event folder then and compare it to mine.

The error you got sounds like an old graphic card needing an update.

**Comment by maptap** [comment]
Thanks for the response!

The version I have I got through subscribing on steam. I attached it here.

[(7) Community Events (v 4).zip](https://github.com/TechpriestEnginseer/Community-Patch-Events-Development/files/1602274/7.Community.Events.v.4.zip)

How do I update my graphics card?

**Comment by TechpriestEnginseer** [comment]
https://www.wikihow.com/Update-Your-Video-Card-Drivers-on-Windows-7

Looking at the Community Events, there's no noticeable glitches.

**Comment by maptap** [comment]
After updating it worked! Thanks!
