### ISSUE TITLE
Great Generals/Admirals not increasing supply limit

### ISSUE THREAD

**Issue by Serind92** [TechpriestEnginseer/Community-Patch-Events-Development#63]
As Greece at least didn't check with other civilizations .

**Comment by TechpriestEnginseer** [comment]
This should be a general concern in the DLL no?

**Comment by Serind92** [comment]
I'm Completely green on this. Only other mods (other than full VP with EUI) i use are Quick Turns and Really Advanced Setup, so i don't think it's a conflict or smth.

Also in game without CBP events (https://forums.civfanatics.com/threads/cbp-events-and-decisions-compatibility.562935/page-20#post-14768793 and this http://steamcommunity.com/sharedfiles/filedetails/?id=689787148 download ) everything works fine.

Edit. Posted links cause maybe i forgot to downlaod smth.

**Comment by TechpriestEnginseer** [comment]
Interesting. It shouldn't be interfering with GG code at all. I'll try to replicate how many Greek events are active?

**Comment by Serind92** [comment]
Tried now with Rome, same issue. But with Rome i was also using this mod 

https://forums.civfanatics.com/resources/more-unique-components-for-vox-populi.26513/

About Greek game if i recall correctly 1st citadel was before 1st Greek specific events and still it didn't give + 2 limit.

**Comment by Serind92** [comment]
About Greek game if i recal correctly 1st citadel was before 1st Greek specific events and still it didn;t count.

**Comment by TechpriestEnginseer** [comment]
Were you using Greeks with the more UC as well

**Comment by Serind92** [comment]
I've found out what caused this bug. Newest Hotfix to VP, unlucky i installed it together with this mod so it completely confused me ;D. sorry for taking your time and thx for trying to help.
