### ISSUE TITLE
When used in an MP modpack, all sound is disabled.

### ISSUE THREAD

**Issue by stevenkxu** [TechpriestEnginseer/Community-Patch-Events-Development#64]
I used the Multiplayer Modpack Workaround mod to set up a custom modpack including this mod (version with 141 events), but when I do so there is no in-game sound. If I create a modpack excluding this mod, and only this mod, there is sound.

Other mods used:
- Wonders Expanded
- Civic and Reform
- More Unique Components for VP
- UI - Improved City View (Vox Populi EUI version)
- Unique City-States
- VP Promo Icons
- World Congress Reformation 

I am relatively sure that this mod is the culprit, but I have no idea why. A poster on the MPMPM thread also found that this mod caused an audio problem, but I can't find that post anymore. What information would be necessary to determine if this mod is the cause?

**Comment by TechpriestEnginseer** [comment]
This mod is the cause and I have noticed the problem when addressed within a few of my testers. Just finding the time to update the mod now.

**Comment by MoiMagnus** [comment]
Is it fixed?

**Comment by TechpriestEnginseer** [comment]
It should be if you delete all the audio files.

**Comment by TechpriestEnginseer** [comment]
Did I answer your question?

**Comment by MoiMagnus** [comment]
Didn't tried yet. (I've tried without deleting the audio files, and the bug was worst than just no sound, it was "impossible to select promotions because sound for promotion not found", making it completely unplayable with a modpack)

**Comment by TechpriestEnginseer** [comment]
wat.

how exactly is EventAudio.xml in (1)\Core Files\Core Tables converted to a DLC file?

Along with (1)\Core Files\CoreLua\EventChoice.mp3?

**Comment by MoiMagnus** [comment]
The error is "Runtime Error: Sound cannot be found", and prevent to select a promotion.

Step to reproduce:
1) Use this modpack (contain only VP, community events, and IGE): https://mega.nz/#F!kfwxRaCA!sYizro3avJ34fHBfbhs3nw 
=> The one named "events" contain your mod. The one named "EUI" does not, so you can compare them.
2) Start a new game (single player)
3) Play until having a promotion, or use IGE to give the promotion to the pathfinder.
4) Fail to be able to procede any longer because of the missing sound.

**Comment by MoiMagnus** [comment]
(From an outside point of view, the sound is treated the same way by VP and by your mod: both mp3 files are copied and in both case an override .xml file is created for the sound, so I don't know what causes the problem)

**Comment by TechpriestEnginseer** [comment]
Are you sure you're not using an outdated Events?

**Comment by MoiMagnus** [comment]
I use the v4, the one on Steam.

**Comment by TechpriestEnginseer** [comment]
Yeah, but the version(usually because it's a hotfix) does change multiple times. I believe the cannot find audio is in one of the older versions and not the updated one.

https://steamcommunity.com/sharedfiles/filedetails/changelog/689787148

**Comment by MoiMagnus** [comment]
Is it written somewhere in the mod files?
It should have been updated automatically by steam since I'm subscribed, at least to the 22/11 version (not sure for the 25/11 one)

**Comment by TechpriestEnginseer** [comment]
just unsubscribe and re-subscribe

**Comment by MoiMagnus** [comment]
You were correct, the last version work correctly. (But steam does not update alone)

**Comment by TechpriestEnginseer** [comment]
It doesn't auto-update, but has an update button next to the mod when given so.
