### ISSUE TITLE
Foreiner murdered

### ISSUE THREAD

**Issue by slinkydinky66** [TechpriestEnginseer/Community-Patch-Events-Development#66]
![20181208152002_1](https://user-images.githubusercontent.com/45721804/49691089-ae70cd00-fb00-11e8-991c-37326caf62ce.jpg)
![20181208152159_1](https://user-images.githubusercontent.com/45721804/49691090-ae70cd00-fb00-11e8-94f8-1293589349e4.jpg)
![20181208152212_1](https://user-images.githubusercontent.com/45721804/49691091-ae70cd00-fb00-11e8-9491-0c4456e0dc7f.jpg)
Dropped to negative Great diplomat points after event?

**Comment by TechpriestEnginseer** [comment]
Yikes, I'll report that to Gazebo. Thank you for reporting!
