### ISSUE TITLE
Event: Swords to Plowshares

### ISSUE THREAD

**Issue by AnastaseAlex** [TechpriestEnginseer/Community-Patch-Events-Development#7]
Requires: negative gold per turn, military unit maintenance > buildings maintenance, 2 melee units of level 2+era.

Text: The economy is crumbling under the strain of feeding our inactive military!

Case1: Resettle them! 
(2 melee units of level 2+era are deleted) the closest city to each deleted unit acquires 2 two free tiles!

Case2: No cost will be spared for the glory of our army! Levy more taxes!
Cities produce +2 gold and get +2 local unhappyness (taxes) for 7 turns.

**Comment by TechpriestEnginseer** [comment]
Done. I haven't tested it, but it's a city event. The garrison is deleted in exchange for local culture(not sure how local culture work, but it should be basically how city grow and should not be related to national culture) However, if you refuse this option, your alternative is to produce 2 more extra gold in exchange for 2 more unhappiness.

Adding this in the Community Event section.
