### ISSUE TITLE
Event: Atoll Lighthouse

### ISSUE THREAD

**Issue by AnastaseAlex** [TechpriestEnginseer/Community-Patch-Events-Development#9]
Requires: city works on an atoll tile

Text: Lights were coming from that atoll last night!

Case1: They are the spirits of the island, we need to consecrate our shrine to them!
Requires shrine, gives +1 faith to shrine.

Case2: They are pirates! We need to take them out!
Requires garrisoned ship, gain a great admiral, 3 barbarian ships spawn around the city.

Case3: They are pirates!
3 barbarian ships spawn around the city.

Case4: The ship which reported this would have been stranded at see without these lights... Perhaps we should always have a fire there?
City must not have a lighthouse, Spend 250 gold, a lighthouse is built in the city.

Case5: A flammable material?
Requires research lab, gain 1 oil resource

**Comment by TechpriestEnginseer** [comment]
I'm not sure if we have the events that checks if a feature is within the city's radius nor can we tell if there's a garrisoned ship since ships aren't garrisons.

**Comment by Hokath** [comment]
There is NearbyFeature which takes FEATURE_ATOLL or similar
Ships cant be done though

**Comment by AnastaseAlex** [comment]
then require garrison should also be ok, I guess and reduce the number of barbarian ships appearing?

**Comment by TechpriestEnginseer** [comment]
Closed due to inactivity.
